# Generated by Django 2.1.8 on 2019-06-01 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('help_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('room_name', models.CharField(max_length=100)),
                ('room_description', models.TextField()),
                ('room_price', models.IntegerField()),
                ('room_capacity_cnt', models.IntegerField()),
                ('room_bedroom_cnt', models.IntegerField()),
                ('room_bathroom_cnt', models.IntegerField()),
                ('room_bed_cnt', models.IntegerField()),
                ('room_self_checkin', models.BooleanField()),
                ('is_checkin_good', models.BooleanField()),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('gu', models.CharField(max_length=20)),
                ('is_super_host', models.BooleanField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to=settings.AUTH_USER_MODEL)),
                ('room_facility', models.ManyToManyField(to='rooms.Facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('photo', models.ImageField(upload_to='room/')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_photos', to='rooms.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
