# Generated by Django 2.1.8 on 2019-06-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20190601_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_facility',
            field=models.ManyToManyField(blank=True, to='rooms.Facility'),
        ),
    ]
