# Generated by Django 2.1.8 on 2019-06-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20190601_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_good_checkin',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_description',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_facility',
        ),
        migrations.AddField(
            model_name='room',
            name='room_detail_guest_access',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_detail_guest_interaction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_detail_others',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_detail_space',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_detail_summary',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
