# Generated by Django 2.1.8 on 2019-06-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20190601_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_bathroom_cnt',
            new_name='bathroom_cnt',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_bed_cnt',
            new_name='bed_cnt',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_bedroom_cnt',
            new_name='bedroom_cnt',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_capacity_cnt',
            new_name='capacity_cnt',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_detail_guest_access',
            new_name='detail_guest_access',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_detail_guest_interaction',
            new_name='detail_guest_interaction',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_detail_others',
            new_name='detail_others',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_detail_space',
            new_name='detail_space',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_detail_summary',
            new_name='detail_summary',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='address',
            new_name='map_address',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='room',
            name='gu',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_self_checkin',
        ),
        migrations.AddField(
            model_name='room',
            name='location_info',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='amenity',
            field=models.ManyToManyField(to='rooms.Amenity'),
        ),
    ]
