# Generated by Django 2.1.8 on 2019-06-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20190601_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='map_address',
        ),
        migrations.AddField(
            model_name='room',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
