# Generated by Django 2.1.8 on 2019-06-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_room_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
