# Generated by Django 2.1.8 on 2019-06-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomphoto',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
