# Generated by Django 2.1.8 on 2019-06-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20190603_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomphoto',
            name='photo',
            field=models.ImageField(upload_to='room/'),
        ),
    ]
