# Generated by Django 2.1.8 on 2019-06-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_remove_room_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='bathroom_cnt',
            new_name='bathroom',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='bed_cnt',
            new_name='bed',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='bedroom_cnt',
            new_name='bedroom',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='capacity_cnt',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_super_host',
        ),
        migrations.RemoveField(
            model_name='room',
            name='location_info',
        ),
    ]
