# Generated by Django 2.1.8 on 2019-06-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_auto_20190612_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='detail_guest_access',
            new_name='room_info_1',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='detail_guest_interaction',
            new_name='room_info_2',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='detail_others',
            new_name='room_info_3',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='detail_space',
            new_name='room_info_4',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='detail_summary',
            new_name='summary',
        ),
    ]
