# Generated by Django 2.1.8 on 2019-06-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0017_auto_20190612_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_info_4',
            new_name='room_info_0',
        ),
    ]
