# Generated by Django 2.1.8 on 2019-06-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0018_auto_20190612_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
